on:
  push:
    branches:
      - main

jobs:
  run-action:
    runs-on: ubuntu-latest
    name: Run Check Certificate Action
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Check Certificate Action
        uses: ./
        with:
          apiKey: ${{ secrets.WEBSITE_ORACLE_API_KEY }}
          host: "cadmus-labs.github.io"

  trigger-on-external-repo:
    runs-on: ubuntu-latest
    name: Trigger on External Repo
    permissions:
      actions: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Trigger Workflow
        run: |
          curl -L --fail-with-body --request POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CADMUS_LABS_CICD_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --url https://api.github.com/repos/cadmus-labs/cadmus-labs.github.io/actions/workflows/website-oracle-checks.yaml/dispatches \
            -d '{"ref":"main"}'
